function m(b,a,c,d){b.m.ob(b.sb,a,c,d)}function n(b,a,c,d){b.m.da?m(b,a,c,d):b.m.Se()._OnMessageFromDOM({type:"event",component:b.sb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.sb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Wb||(b.m.Bc(b.ie),b.Wb=!0)}window.ib=class{constructor(b,a){this.m=b;this.sb=a;this.Wb=!1;this.ie=()=>this.Pa()}pd(){}Pa(){}};
window.Df=class{constructor(){this.kd=-1}j(){-1!==this.kd&&(self.clearTimeout(this.kd),this.kd=-1)}};"use strict";class aa{constructor(b){this.vb=b;this.Rc=!1;this.Yc=!0;this.xb=this.pa=this.ld=-1}}
function ba(b,a){const c=a.elementId,d=b.td(c,a),e=new aa(d);b.Ha.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Yc=!!a.isVisible;var f=b.Ec(d);f.addEventListener("focus",()=>{ca(b,"elem-focused",c)});f.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});f=a.htmlIndex;e.ld=f;e.xb=a.htmlZIndex;b.Sa&&(a=b.m.sc(f),e.pa=a,b.m.Mb(a).appendChild(d))}function da(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}
function x(b,a){b=b.Ha.get(a);if(!b)throw Error(`no element with id ${a}`);return b.vb}function ca(b,a,c){var d;d||(d={});d.elementId=c;m(b,a,d)}
window.rc=class extends self.ib{constructor(b){super(b,"button");this.Ha=new Map;this.Sa=!0;v(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=x(this,a);this.Sa&&c.parentElement.removeChild(c);this.Ha.delete(a)}],["set-visible",a=>{if(this.Sa){var c=this.Ha.get(a.elementId),d=c.vb;c.Rc?d.style.display=a.isVisible?"":"none":c.Yc=!!a.isVisible}}],["update-position",a=>{if(this.Sa){var c=this.Ha.get(a.elementId),d=c.vb,e=this.m;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.ld=f;f=e.sc(f);f!==c.pa&&(d.remove(),e.Mb(f).appendChild(d),c.pa=f,e.Lc());a=a.htmlZIndex;a!==c.xb&&(c.xb=a,e.Lc());c.Rc||(c.Rc=!0,c.Yc&&(d.style.display=""))}}],["update-state",a=>{const c=x(this,a.elementId);this.Ac(c,a)}],["focus",a=>{const c=this.Ec(x(this,a.elementId));a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=x(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,
a):c.style[d]=a}],["set-attribute",a=>{x(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{x(this,a.elementId).removeAttribute(a.name)}]]);da(this,a=>a)}td(){throw Error("required override");}Ac(){throw Error("required override");}Ec(b){return b}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let fa=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.tf?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.xf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ha(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ia={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,la=new Map;let ma=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.Oa=class b{constructor(a){this.da=a.zf;this.xa=null;this.aa="";this.bb=a.wf;this.Kb={};this.Wa=this.ua=null;this.Ua=[];this.ma=null;this.Wd=!0;this.M=[];this.dd=[];this.ed=!1;this.je=()=>this.Qe();this.Vc=!1;this.Qd=0;this.zb=null;this.ab=-1;this.pf=()=>this.af();this.Hb=new Set;this.md=null;this.ke=[];this.A=a.le;this.Xb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===this.A&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.Ma()?self.chrome.webview.addEventListener("message",c=>this.Fd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Fd(c));this.$b=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.ef(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.We());this.B("runtime","cordova-fetch-local-file",c=>this.Xe(c));this.B("runtime","create-job-worker",()=>this.Ye());this.B("runtime","send-wrapper-extension-message",c=>this.df(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Dd(a)):this.Dd(a)}j(){this.Cc();this.xa&&(this.xa=this.xa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Wa&&(this.Wa.j(),this.Wa=null);for(const {canvas:a,
fb:c}of this.M)a.remove(),c.remove();this.M.length=0}vd(){return this.M[0].canvas}sc(a){return Math.min(a,this.M.length-1)}Mb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].fb}Ge(){return ea&&"cordova"===this.A}mb(){const a=navigator.userAgent;return ea&&qa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ee(){return y}wd(){return y&&qa.has(this.A)}yd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Ma(){return this.yd()||"xbox-uwp-webview2"===this.A}async Dd(a){this.da&&!await ha()&&(this.da=!1);"macos-wkwebview"===this.A?this.pb({type:"ready"}):this.Ma()&&(this.gf(),this.ke=(await this.Ve()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.$b={};await this.Ne();for(let d=0,e=a.eb.length;d<e;++d){var c=a.eb[d];this.$b.hasOwnProperty(c)?a.eb[d]={tf:!0,xf:this.$b[c]}:this.ra.hasOwnProperty(c)&&(a.eb[d]=URL.createObjectURL(this.ra[c]))}a.oc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Bc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.vf?this.aa=a.vf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Bf&&(this.Kb=a.Bf);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.$e(d));this.zb=
new self.He(this);await sa(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Ue(a,c.port2):await this.Te(a,c.port2)}Fc(a){a=this.Kb.hasOwnProperty(a)?this.Kb[a]:a.endsWith("/workermain.js")&&this.Kb.hasOwnProperty("workermain.js")?this.Kb["workermain.js"]:"playable-ad"===
this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Xb)return a=await this.Lb(d.sf?a:this.bb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Cd(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.lb(),k=a.Gf,l=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.le;var u=(new URLSearchParams(self.location.search)).has("debug"),B=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Ff,jobScheduler:{inputPort:B.Uc,outputPort:B.cd,maxNumWorkers:B.lf},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.bb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.bb+"opus.wasm.wasm",isFileProtocol:this.Xb,isiOSCordova:this.Ge(),isiOSWebView:this.mb(),isWindowsWebView2:this.yd(),isAnyWebView2Wrapper:this.Ma(),wrapperComponentIds:this.ke,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ue(a,c){const d=this.Fc(a.Af);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ua.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ua.addEventListener("message",r);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ua=await this.qc(d,this.aa,{type:"module",name:"Runtime",sf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,fb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.oc||[],k=a.eb;h=await Promise.all(h.map(l=>this.Qa(l)));k=await Promise.all(k.map(l=>this.Qa(l)));if("cordova"===this.A)for(let l=0,p=a.nc.length;l<p;++l){const r=
a.nc[l],t=r[0];if(t===a.nd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Qa(t)}this.ua.postMessage(Object.assign(this.Cd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.nc,mainProjectScript:a.nd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ta(this.zb)]);this.Ua=F.map(l=>new l(this));this.Bd();ua(e);va(g);wa(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.zd(r.sb,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.ob("runtime","go-to-last-error-script"))}async Te(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,fb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ua=F.map(h=>new h(this));this.Bd();ua(d);va(e);e=a.eb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.oc)){var f=[...a.oc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Qa(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.nd;const g=a.nc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Qa(k),await z(k),"preview"!==this.A||e[h]||this.Hd(h,"main script did not run to completion")}catch(l){this.Hd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Qa(k),await z(k);"preview"===this.A&&"object"!==typeof self.Cf.Ef?(this.Rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Cd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:pa}),wa(this.ma),this.Ed(),this.Wa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Wa,
a))}Hd(a,c){this.Rb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Rb()}Rb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ye(){const a=await xa(this.zb);return{outputPort:a,transferables:[a]}}ef(a){if(!this.Vc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,fb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Wd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Wd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,fb:p}=this.M.pop();p.remove();this.da&&!d?this.dd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ua(c),va(d),this.M.push({canvas:c,fb:d});for(const l of this.Ua)if(l instanceof window.rc&&l.Sa)for(const p of l.Ha.values())e=l.m.sc(p.ld),f=p.pa,-1!==e&&-1!==f&&e!==f&&(f=p.vb,f.remove(),l.m.Mb(e).appendChild(f),p.pa=e);this.Lc();return{addedCanvases:a,transferables:k}}We(){for(const a of this.dd)a.remove();this.dd.length=0}Lc(){this.ed||(this.ed=!0,this.Bc(this.je))}Qe(){this.Gd(this.je);
this.ed=!1;let a=[];for(var c of this.Ua)if(c instanceof window.rc){var d=c.Sa?[...c.Ha.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.pa,l=h.pa;return k!==l?k-l:g.xb-h.xb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.pa!==c&&(this.Ad(c,a.slice(d,e)),c=g.pa,d=e)}d<e&&this.Ad(c,a.slice(d,e))}Ad(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.vb);var d=new Set(c);a=this.Mb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Se(){if(this.da)throw Error("not available in worker mode");return this.Wa}ob(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}zd(a,c,d,e,f){const g=ma++,h=new Promise((k,l)=>{la.set(g,{resolve:k,reject:l})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ze(a);if("result"===c)this.bf(a);else if("runtime-ready"===c)this.cf();else if("alert-error"===c)this.Rb(),alert(a.message);else if("creating-runtime"===c)this.Ed();else throw Error(`unknown message '${c}'`);}Ze(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Qb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Qb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Qb(f,!1,""+h)}):this.Qb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Qb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}bf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=la.get(c);d?e.resolve(a):e.reject(a);la.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static gb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}Bd(){for(const a of this.Ua)if("runtime"===a.sb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}$e(a){this.ob("debugger","message",a)}cf(){for(const a of this.Ua)a.pd()}static lb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static Id(a){ra=!!a}Bc(a){this.Hb.add(a);
this.Kc()}Gd(a){this.Hb.delete(a);0===this.Hb.size&&this.Cc()}Kc(){-1===this.ab&&0<this.Hb.size&&(this.ab=requestAnimationFrame(this.pf))}Cc(){-1!==this.ab&&(cancelAnimationFrame(this.ab),this.ab=-1)}af(){this.ab=-1;for(const a of this.Hb)a();this.Kc()}Da(a){this.ma.Da(a)}Na(a){this.ma.Na(a)}Jc(){this.ma.Jc()}Pb(a){this.ma.Pb(a)}Fe(){return!!ia["audio/webm; codecs=opus"]}async hf(a){a=await this.zd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Je(a){this.Vc=!0;this.Qd=
a}De(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}xd(a){return!this.De(a)}async Qa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Xb&&this.xd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Lb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Xe(a){const c=a.filename;switch(a.as){case "text":return await this.Ce(c);case "buffer":return await this.Lb(c);default:throw Error("unsupported type");
}}sd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ce(a){a=await this.sd(a);return await ja(a)}Dc(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.Oe(a.filename,a.yf,a.rf)}}Lb(a){return new Promise((c,d)=>{C.push({filename:a,yf:e=>{E--;this.Dc();c(e)},rf:e=>{E--;this.Dc();d(e)}});this.Dc()})}async Oe(a,c,d){try{const e=await this.sd(a),f=await ka(e);c(f)}catch(e){d(e)}}Fd(a){if("entered-fullscreen"===
a)b.Id(!0),H(this.ma);else if("exited-fullscreen"===a)b.Id(!1),H(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.md(a),this.md=null):"extension-message"===c?this.ob("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}df(a){this.pb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}pb(a){this.Ma()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}gf(){window.moveTo=(a,c)=>{this.pb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.pb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ve(){return this.Ma()?new Promise(a=>{this.md=a;this.pb({type:"wrapper-init"})}):Promise.resolve()}async Ne(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.Me(c,d));
await Promise.all(a)}async Me(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.$b[a]=c.str;else{let d=await this.Re(c);d||(d=this.Pe(c));this.ra[a]=d}}async Re(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Pe(a){a=this.ff(a);return this.Le(a.data,
a.uf)}ff(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{uf:a,data:d}}Le(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const I=self.Oa,ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},Aa={dispatchRuntimeEvent:!0};function Ba(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ca(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function K(b){b=URL.createObjectURL(b);try{return await Ca(b)}finally{URL.revokeObjectURL(b)}}function Da(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ea(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Da(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Fa(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ga=new Set(["input","textarea","datalist","select"]),Ha=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ha.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ia(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ja(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ea(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function ua(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function va(b){b.addEventListener("selectstart",Ia);b.addEventListener("gesturehold",Ia);b.addEventListener("touchstart",Ia)}function wa(b){b.Pd=!0;b.Zc=b.m.oa();b.Ab=b.m.ga()}
function H(b){if(!b.ka){var a=I.lb();a&&"any"!==b.hd&&La(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ma(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Na(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Pa(b){return await self.C3_GetSvgImageSize(b.blob)}function Qa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ra(b){self.setTimeout(()=>{b.Od=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Sa(b,!0)),document.addEventListener("resume",()=>Sa(b,!1))):document.addEventListener("visibilitychange",()=>Sa(b,"hidden"===document.visibilityState));b.dc=!("hidden"!==document.visibilityState&&!Ka);return{isSuspended:b.dc}}
function Ta(b){b.Kd||(b.Kd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ua(b){b.Jd||(b.Jd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Va(b){await Ba(b.url)}
function Wa(b,a){b.Rd=a.message;-1===b.Pc&&(b.Pc=setTimeout(()=>{b.Pc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Rd)},250))}function Xa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.lb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Sa(b,a){b.dc!==a&&((b.dc=a)?b.m.Cc():b.m.Kc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.mb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ya(b,a,c){"Backspace"===c.key&&L(c);if(b.m.Ma()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=ya.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J))}
function M(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.ad);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.ad=c.buttons)}}function Za(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Aa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Aa=a))}}
function $a(b,a,c,d){const e=b.oa(),f=b.ga();b.cb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.lb()}):10>d&&ab(b,e,f,d+1)}function ab(b,a,c,d){-1!==b.cb&&clearTimeout(b.cb);b.cb=setTimeout(()=>$a(b,a,c,d),48)}
function La(b){b=b.hd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.gb(class extends self.ib{constructor(b){super(b,"runtime");this.Pd=!1;this.cb=-1;this.hd="any";this.dc=this.Jd=this.Kd=!1;this.kc=document.createElement("div");this.kc.className="c3-screen-reader-text";this.kc.setAttribute("aria-live","polite");document.body.appendChild(this.kc);this.Ga=null;this.ka=!1;this.Rd="";this.Pc=-1;this.Od=!1;this.Zc=b.oa();this.Ab=b.ga();this.Aa=this.Jb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ma(c));b.B("runtime","raster-svg-image",c=>Na(c));b.B("runtime","get-svg-image-size",c=>Pa(c));b.B("runtime","set-target-orientation",c=>{this.hd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Qa(c));b.B("runtime","go-to-script",c=>Qa(c));b.B("runtime","before-start-ticking",()=>Ra(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ta(this));b.B("runtime","enable-device-motion",()=>Ua(this));b.B("runtime","add-stylesheet",c=>Va(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.kc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.vd().style.display="";this.m.Je(c.duration)});b.B("runtime","export-to-video-progress",c=>Wa(this,c));b.B("runtime","exported-to-video",c=>{window.qf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.qf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Fa(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.ad=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Pd){var c=this.oa();var d=this.ga();if(this.m.wd()){if(this.Od){if(this.Zc===
c&&d<this.Ab){this.Jb=this.Ab-d;Za(this,this.Ab,this.Jb);c=void 0;break a}0<this.Jb&&(this.Jb=0,Za(this,d,this.Jb))}this.Zc=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.lb()});this.m.mb()&&(-1!==this.cb&&clearTimeout(this.cb),$a(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",c=>Xa(this,c));window.addEventListener("webkitfullscreenerror",c=>Xa(this,c));window.addEventListener("mozfullscreenerror",c=>Xa(this,c));if(b.mb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Fa(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Xa=new Set;this.bc=new WeakSet;this.wa=!1}pd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Aa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Aa);this.ad=0});window.addEventListener("focusin",a=>{a=a.target;(Ga.has(a.tagName.toLowerCase())||Fa(a))&&m(this,"keyboard-blur",null,Aa)});window.addEventListener("keydown",a=>Ya(this,"keydown",a));window.addEventListener("keyup",a=>Ya(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,za));window.addEventListener("mousemove",a=>M(this,"mousemove",a,za));window.addEventListener("mouseup",a=>M(this,"mouseup",a,za));window.addEventListener("dblclick",
a=>M(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Aa,pageX:a.pageX,pageY:a.pageY+this.Aa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();bb(a.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.m.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Jc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.m.Ee()&&!this.m.wd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Za(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.mb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.m.oa()}ga(){return this.m.ga()}Jc(){var b=[...this.Xa];this.Xa.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.bc.has(a)||this.Xa.add(a)})}Da(b){if("function"!==
typeof b.play)throw Error("missing play function");this.bc.delete(b);let a;try{a=b.play()}catch(c){this.Xa.add(b);return}a&&a.catch(()=>{this.bc.has(b)||this.Xa.add(b)})}Na(b){this.Xa.delete(b);this.bc.add(b)}Pb(b){this.wa=!!b}});"use strict";
async function sa(b){if(b.jf)throw Error("already initialised");b.jf=!0;var a=b.ya.Fc(("playable-ad"===b.ya.A?b.ya.bb:"")+"dispatchworker.js");b.Oc=await b.ya.qc(a,b.rb,{name:"DispatchWorker"});a=new MessageChannel;b.Uc=a.port1;b.Oc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.cd=await xa(b)}function ta(b){return[b.Uc,b.cd]}
async function xa(b){const a=b.Xd.length;var c=b.ya.Fc(("playable-ad"===b.ya.A?b.ya.bb:"")+"jobworker.js");c=await b.ya.qc(c,b.rb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Oc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Xd.push(c);return e.port1}
self.He=class{constructor(b){this.ya=b;this.rb=b.aa;this.rb="preview"===b.A?this.rb+"workers/":this.rb+b.bb;this.lf=Math.min(navigator.hardwareConcurrency||2,16);this.Oc=null;this.Xd=[];this.cd=this.Uc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Oa({zf:!0,Af:"workermain.js",eb:["scripts/c3runtime.js"],nc:[],nd:"",wf:"scripts/",oc:[],le:"html5"}));"use strict";
async function cb(b,a){a=a.type;let c=!0;0===a?c=await db():1===a&&(c=await eb());m(b,"permission-result",{type:a,result:c})}async function db(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function eb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Oa.gb(class extends self.ib{constructor(b){super(b,"touch");q(this,"request-permission",a=>cb(this,a))}});"use strict";const fb=180/Math.PI;
async function gb(b,a){if(a.isiOSCordova||a.isSafari)b.fc=!0;b.jd=a.timeScaleMode;b.be=["equalpower","HRTF","soundfield"][a.panningModel];b.Nd=["linear","inverse","exponential"][a.distanceModel];b.ce=a.refDistance;b.ae=a.maxDistance;b.ee=a.rolloffFactor;if(b.m.Vc)b.fc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Qd)});else{var c={latencyHint:a.latencyHint};b.he||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");jb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&jb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ta=b.g.createGain();b.Ta.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function kb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Yd=g.slice(0);lb(b,g);try{b.R=await mb(b,c,d,e,g,f);if(p){P(b.R,!0);var u=b.R,B=p.innerAngle,na=p.outerAngle,oa=p.outerGain;if(u.yb){nb(u,p.x,p.y,p.z,p.angle);var D=self.hb.Ke;u.sa[0]!==D(B)&&
(u.sa[0]=D(B),u.F.coneInnerAngle=D(B));u.sa[1]!==D(na)&&(u.sa[1]=D(na),u.F.coneOuterAngle=D(na));u.sa[2]!==oa&&(u.sa[2]=oa,u.F.coneOuterGain=oa)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),ob(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(Ab){console.error("[Construct] Audio: error starting playback: ",Ab);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.od--;0===d.od&&(d.resolve(),b.Gb.delete(c))}w(b)}
async function pb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await qb(b,c);for(const h of R(b,c))if(!h.va){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Va=g;h.ge=a}S(b)}async function rb(b,a){const c=a.tags;a=a.rate;await qb(b,c);for(const d of R(b,c))d.la!==a&&(d.la=a,d.Ea())}async function sb(b,a){const c=a.tags;a=a.pos;await qb(b,c);for(const d of R(b,c))d.xc(a)}
async function tb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await mb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ub(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function vb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.re(b,...e);else if("delay"===c)d=new self.pe(b,...e);else if("convolution"===c){var g=d=new self.oe(b,f.ha,...e),h=a.bufferType;g.Ld=a.bufferOriginalUrl;g.Md=h}else if("flanger"===c)d=
new self.se(b,...e);else if("phaser"===c)d=new self.ue(b,...e);else if("gain"===c)d=new self.te(b,...e);else if("stereopan"===c)d=new self.we(b,...e);else if("tremolo"===c)d=new self.xe(b,...e);else if("ringmod"===c)d=new self.ve(b,...e);else if("distortion"===c)d=new self.qe(b,...e);else if("compressor"===c)d=new self.ne(b,...e);else if("analyser"===c)d=new self.me(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Vd=l.length;d.gd=
h;l.push(d);wb(g,h)}xb(b)}
async function yb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.lc=a.timeScale;b.Qc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.wa=a.isSilent;b.m.Pb(b.wa);b.ac=a.masterVolume;b.Ta.gain.value=
b.ac;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>vb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>zb(b,f,c)));S(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Ud?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.ob("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.Ud=!0);await c}catch(c){Cb(c)}}
function jb(b){b.Vb||(b.Tc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Vb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ia)if(g.kb()===c)return await Db(g),g;if(f)return null;if(e&&(b.fc||b.Td)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Ba()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.he;e&&f&&(b.Td=!0);c=!e||b.fc||f?new self.Ae(b,a,c,d,e,f):new self.ye(b,a,c,d,e);b.ia.push(c);await Db(c);b.$d.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.$d.add(a));return c}
function Eb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Fb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function wb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Gb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.$c===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Gb(b,a){if(a)for(const c of b.H)Eb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Hb(b,a,c){return c?b.m.hf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ib(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Eb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function mb(b,a,c,d,e,f){for(const g of b.H)if(g.kb()===c&&(g.pc()||f))return g.na=e,g;a=await O(b,a,c,d,f);e="html5"===a.Mc?new self.ze(a.u,a,e):new self.Be(a.u,a,e);b.H.push(e);return e}
function lb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={od:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.od++}function qb(b,a){return(b=b.Gb.get((0===a.length?b.Yd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ra.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Jb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function xb(b){b.Wc||(b.Wc=!0,Promise.resolve().then(()=>Kb(b)))}
function Kb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.jb());m(b,"fxstate",{fxstate:a});b.Wc=!1}
async function zb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await mb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],f=d.orient,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],e.setPosition(...b.Za),e.setOrientation(...b.Ya),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),ob(b,d));c.Play(k,l,p,0);a.isPlaying||c.nb();c.Hc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.hb=class extends self.ib{constructor(b){super(b,"audio");this.Ta=this.g=null;this.Vb=this.Tc=!1;this.za=()=>{if(!this.Tc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Vb&&(this.Tc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Vb=!1)}};this.ia=[];this.H=[];this.R=null;this.Yd=[];this.$d=new Set;this.Zd=-1;this.Gb=new Map;this.ac=1;this.wa=!1;this.jd=0;this.lc=1;this.Qc=0;this.be="HRTF";this.Nd="inverse";this.ce=600;this.ae=1E4;this.ee=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Td=this.fc=!1;this.he=this.m.Fe();this.ja=new Map;this.Ra=new Set;this.Ud=this.Wc=!1;this.$c="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.$c=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Fb(this,this.$c))};this.Ub=null;self.C3Audio_GetOutputStream=()=>{this.Ub||(this.Ub=this.g.createMediaStreamDestination(),this.Ta.connect(this.Ub));return this.Ub.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>gb(this,a)],["play",a=>kb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.nb():d.Ob();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>pb(this,a)],["set-master-volume",a=>{this.ac=a.vol;this.Ta.gain.value=this.ac}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Lb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.m.Pb(this.wa);for(const c of this.H)c.Sb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.yc(a)}],["set-playback-rate",a=>rb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),ob(d,a)}],["seek",a=>sb(this,a)],["preload",a=>tb(this,a)],["unload",a=>ub(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.zc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>vb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);xb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);wb(this,a)}}],["tick",a=>{this.lc=a.timeScale;this.Qc=a.gameTime;this.Zd=a.tickCount;if(0!==this.jd)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&nb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>yb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Ta}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Nb(){return this.wa}Da(b){this.m.Da(b)}Na(b){this.m.Na(b)}Pa(){for(var b of this.Ra)b.Pa();
b=this.g.currentTime;for(var a of this.H)a.Pa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.jb());m(this,"state",{tickCount:this.Zd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ra].map(c=>({tag:c.gd,index:c.Vd,peak:c.$a,rms:c.de,binCount:c.l.frequencyBinCount,freqBins:c.Sd}))});0===a.length&&0===this.Ra.size&&this.Wb&&(this.m.Gd(this.ie),this.Wb=!1)}static Ke(b){return b*fb}static ud(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ie(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Oa.gb(self.hb);"use strict";function Db(b){b.Zb||(b.Zb=b.Gc());return b.Zb}self.qd=class{constructor(b,a,c,d,e){this.u=b;this.nf=a;this.Ja=c;this.T=d;this.kf=e;this.Mc="";this.Zb=null}j(){this.Zb=this.u=null}Gc(){}V(){return this.u.V()}uc(){return this.nf}kb(){return this.Ja}tc(){return this.T}Ba(){return this.kf}fa(){}};"use strict";
self.ye=class extends self.qd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Mc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}j(){Ib(this.u,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Gc(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Mb(b){if(b.Fa)return b.Fa;var a=b.u.m;if("cordova"===a.A&&a.xd(b.Ja)&&a.Xb)b.Fa=await a.Lb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Nb(b){if(b.ha)return b.ha;b.ha=await Hb(b.u,b.Fa,b.mf);b.Fa=null}
self.Ae=class extends self.qd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Mc="webaudio";this.ha=this.Fa=null;this.mf=!!f}j(){Ib(this.u,this);this.ha=this.Fa=null;super.j()}async Gc(){try{await Mb(this),await Nb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Ob=0;
function P(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.be,b.F.distanceModel=b.u.Nd,b.F.refDistance=b.u.ce,b.F.maxDistance=b.u.ae,b.F.rolloffFactor=b.u.ee),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function Q(b,a){a=!!a;b.Yb!==a&&(b.Yb=a,b.Yb?(P(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function ob(b,a){b.Yb&&b.fd!==a&&(b.ca.pan.value=a,b.fd=a)}function T(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Va=-1;b.G.gain.value=b.vc()}function Lb(b,a){a=!!a;b.va!==a&&(b.va=a,b.Sb())}
function nb(b,a,c,d,e){if(b.yb){var f=b.Za,g=b.Ya,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Xc?b.u.Qc:performance.now()/1E3}
self.rd=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Tb=Ob++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.yb=!1;this.Za=[0,0,0];this.Ya=[0,0,0];this.sa=[0,0,0];this.ca=null;this.Yb=!1;this.fd=0;this.I=!0;this.Y=this.ta=this.J=!1;this.Ka=1;this.va=!1;this.la=1;b=this.u.jd;this.Xc=1===b&&!this.Ba()||2===b;this.Va=this.qa=-1;this.ge=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Fb(this.u,0<this.na.length?this.na[0]:"")}uc(){return this.P.uc()}kb(){return this.P.kb()}tc(){return this.P.tc()}Ba(){return this.P.Ba()}O(){}pc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}La(){}fa(){return this.P.fa()}Play(){}Ca(){}nb(){}Ob(){}Pa(b){-1!==this.Va&&b>=this.Va&&(this.Va=-1,this.ge&&this.Ca(),Jb(this.u,"fade-ended",this.na,this.Tb))}vc(){const b=this.Ka;return isFinite(b)?b:0}Nb(){return this.u.Nb()}Sb(){}yc(){}Ea(){}xc(){}zc(){}wc(){}jb(){var b=
this.Tb,a=this.na,c=this.fa(),d=-1===this.Va?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Za,orient:this.Ya,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.uc(),bufferUrl:"",bufferType:this.tc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.va,resumePosition:this.wc(),pan:f,stereoPan:this.ca?
this.fd:null}}Hc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ea());Lb(this,b.isMuted)}};"use strict";
self.ze=class extends self.rd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Ic()}j(){this.Ca();this.P.Fb.disconnect();super.j()}W(){return this.P.W()}Ic(){this.I=!0;this.qa=-1;Jb(this.u,"ended",this.na,this.Tb)}O(){return this.W().ended}pc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.va=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.kb()}' to position '${c}': `,e)}this.u.Da(d);this.J=this.I=!1;this.Y=b;this.la=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Na(b);this.I=!0;this.J=!1;this.qa=-1}nb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Na(b);this.J=!0}}Ob(){!this.J||this.I||this.O()||(this.u.Da(this.W()),this.J=!1)}Sb(){this.W().muted=this.va||this.Nb()}yc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ea(){let b=this.la;this.Xc&&(b*=this.u.lc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}xc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}wc(){return this.La()}zc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.W()),this.ta=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.Be=class extends self.rd{constructor(b,a,c){super(b,a,c);this.s=null;this.cc=d=>this.Ic(d);this.Sc=!0;this.qb=null;this.S=this.ec=this.hc=0;this.bd=1}j(){this.Ca();V(this);this.cc=null;super.j()}Ic(b){this.J||this.ta||b.target!==this.qb||(this.I=this.Sc=!0,this.qa=-1,V(this),Jb(this.u,"ended",this.na,this.Tb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Sc}pc(){return!this.s||this.I?!0:this.O()}La(){let b;b=this.J?this.S:this.ec+(U(this)-this.hc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.va=!1;this.bd=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.cc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Sc=!1;this.Y=b;this.la=1;this.hc=U(this);this.ec=c}Ca(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.qa=-1}nb(){this.J||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Ob(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.cc,this.s.loop=this.Y,T(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.hc=U(this),this.ec=this.S,this.J=!1)}vc(){return super.vc()*this.bd}Sb(){this.bd=this.va||this.Nb()?0:1;T(this,this.Ka)}yc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ea(){let b=this.la;this.Xc&&(b*=this.u.lc);this.s&&(this.s.playbackRate.value=b)}xc(b){this.I||this.O()||(this.J?this.S=b:(this.nb(),
this.S=b,this.Ob()))}wc(){return this.S}zc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.La(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ta=!1:this.ta&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.cc,this.s.loop=this.Y,T(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.hc=U(this),this.ec=this.S,this.ta=!1)}Hc(b){super.Hc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Vd=-1;this.T=this.gd="";this.o=null}j(){this.g=null}N(){}U(){}jb(){return{type:this.T,tag:this.gd,params:this.o}}}
self.re=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.pe=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Db=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ub=W(this);this.ub.gain.value=c;this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i);this.Db.connect(this.X);this.X.connect(this.ub);this.ub.connect(this.Db)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.ub.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.hb.ud;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.ub.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.oe=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Md=this.Ld="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.tb=this.g.createConvolver();this.tb.normalize=c;this.tb.buffer=a;this.v.connect(this.tb);this.v.connect(this.h);this.tb.connect(this.i)}j(){this.v.disconnect();this.tb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}jb(){const b=super.jb();b.bufferOriginalUrl=this.Ld;b.bufferUrl="";b.bufferType=this.Md;return b}};
self.se=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.wb=W(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.wb.gain,a/100,c,d)}}};
self.ue=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.te=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.hb.ud;switch(b){case 4:this.o[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.we=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.l.pan,a,c,d)}}};
self.xe=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ve=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Ib=W(this);this.Ib.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Ib.gain);this.C.start(0);this.v.connect(this.Ib);this.v.connect(this.h);this.Ib.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Ib.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.qe=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=W(this);this.jc=W(this);this.ic=W(this);b=d;.01>b&&(b=.01);this.jc.gain.value=b;this.ic.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.mc=this.g.createWaveShaper();this.Nc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Nc[32768+e]=f,this.Nc[32768-
e-1]=-f;this.mc.curve=this.Nc;this.v.connect(this.jc);this.v.connect(this.h);this.jc.connect(this.mc);this.mc.connect(this.ic);this.ic.connect(this.i)}j(){this.v.disconnect();this.jc.disconnect();this.mc.disconnect();this.ic.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ne=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.me=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Sd=new Float32Array(this.l.frequencyBinCount);this.fe=new Uint8Array(a);this.de=this.$a=0;b=this.u;b.Ra.add(this);S(b)}j(){this.u.Ra.delete(this);this.l.disconnect();super.j()}Pa(){this.l.getFloatFrequencyData(this.Sd);this.l.getByteTimeDomainData(this.fe);const b=this.l.fftSize;let a=this.$a=0;for(var c=0;c<b;++c){let d=(this.fe[c]-
128)/128;0>d&&(d=-d);this.$a<d&&(this.$a=d);a+=d*d}c=self.hb.Ie;this.$a=c(this.$a);this.de=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Z(b){b.stopPropagation()}
self.Oa.gb(class extends self.rc{constructor(b){super(b)}td(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",Z);d.addEventListener("pointerrawupdate",
Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",Z);d.addEventListener("keyup",Z);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;n(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Ac(d,a);return d}Ec(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}Ac(b,a){const c="input"===b.tagName.toLowerCase()?
b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";
self.Oa.gb(class extends self.ib{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.m.vd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
